# Generated by Django 3.0.4 on 2020-03-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20200306_1050'),
    ]

    operations = [
    ]
