# Generated by Django 3.0.13 on 2021-02-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_unique_category_slug'),
        ('categories', '0004_merge_20200312_1831'),
    ]

    operations = [
    ]
